version: '3.8'
services:
  ui:
    build: Microservices/ui
    restart: always
    ports:
     - "80:80"
  rvstore-api-gateway:
    build: Microservices/gateway-service
    restart: always
    ports:
     - "9000:9000"
    environment:
     - SPRING_PROFILES_ACTIVE=compose
  rvstore-auth-api:
    build: Microservices/auth-api
    restart: always
    ports:
     - "9003:9003"
  rvstore-product-api:
    build: Microservices/product-api
    restart: always
    ports:
     - "9001:9001"
    environment:
     - PRODUCT_FILE_LOCATION=/data/products
    volumes:
      - product-data:/data/products
  rvstore-order-api:
    build: Microservices/order-api
    restart: always
    ports:
     - "9002:9002"
    environment:
     - SPRING_PROFILES_ACTIVE=compose
  rvstore-orders-mongodb:
    image: "mongo"
    restart: always
    ports:
     - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
     - MONGO_INITDB_ROOT_PASSWORD=secret
  rvstore-order-simulator:
    build: Microservices/order-simulator
    environment:
     - SPRING_PROFILES_ACTIVE=compose
volumes:
  product-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/Users/tsolley/Google\ Drive/Clients/DI/Docker\ k8s\ 5\ day/rvstore_hackathon"