apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  #minReadySeconds: 40 #comment strategy
  strategy: 
    rollingUpdate: 
      maxSurge: 90%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: vergeops/versioned-nginx:2.0
