apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # ReadOnlyMany, depends on storage type, ReadWriteMany
  resources:
    requests:
      storage: 3Gi