apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mongodb
  template:
    metadata:
      labels:
        app: order-mongodb
    spec:
      containers:
      - name: rvstore-orders-mongodb
        image: mongo
        envFrom:
        - secretRef:
            name: mongodb-secret
# Commented out until you update the path below to be valid.
#        volumeMounts:
#        - mountPath: /data/db
#          name: mongo-volume
        ports:
        - containerPort: 27017
#      volumes:
#      - name: mongo-volume
#        hostPath:
#          path: /Users/tsolley/Desktop/Temp/rvstore-mongodb

---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-orders-mongodb
spec:
  type: ClusterIP
  selector:
    app: order-mongodb
  ports:
  - protocol: TCP
    port: 27017
